# Generated by Django 5.2.7 on 2025-10-29 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('CONDO', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('STUDIO', 'Studio'), ('OFFICE', 'Office'), ('OTHER', 'Other')], db_index=True, default='APARTMENT', max_length=20)),
                ('country', models.CharField(db_index=True, max_length=20)),
                ('street_address', models.CharField(db_index=True, max_length=100)),
                ('post_code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', through='api.PropertyAmenity', to='api.amenity'),
        ),
        migrations.CreateModel(
            name='PropertyImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_bedrooms', models.PositiveSmallIntegerField()),
                ('no_of_bathrooms', models.PositiveSmallIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unit_images/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('is_feature', models.BooleanField(default=False)),
                ('is_floor_plan', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.unit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Property Manager'), ('TENANT', 'Tenant'), ('SEEKER', 'Seeker')], default='SEEKER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='propertyamenity',
            index=models.Index(fields=['property', 'amenity'], name='api_propert_propert_64899d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyamenity',
            index=models.Index(fields=['amenity'], name='api_propert_amenity_ef1e3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyamenity',
            constraint=models.UniqueConstraint(fields=('property', 'amenity'), name='unique_property_amenity'),
        ),
        migrations.AddIndex(
            model_name='unitimage',
            index=models.Index(fields=['unit', 'order'], name='api_unitima_unit_id_e0531b_idx'),
        ),
    ]
