# Generated by Django 5.2.7 on 2025-10-30 03:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = currently active', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('BROKEN', 'Broken')], db_index=True, default='ACTIVE', max_length=10)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='no_of_bathrooms',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='no_of_bedrooms',
            new_name='bedrooms',
        ),
        migrations.AddField(
            model_name='listing',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='promo_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='sqft',
            field=models.PositiveIntegerField(blank=True, help_text='square feet of the unit', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_label',
            field=models.CharField(default=0, help_text='e.g., 3B or #12', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyimg',
            name='img',
            field=models.ImageField(upload_to='property_images/'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'created_at'], name='api_listing_status_f476e1_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property', 'is_available'], name='api_unit_propert_61a4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['rent_amount'], name='api_unit_rent_am_7a1a08_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['available_from'], name='api_unit_availab_4a8f88_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('property', 'unit_label'), name='uniq_unit_per_property'),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='api.unit'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status', 'start_date'], name='api_lease_status_982563_idx'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('unit',), name='one_active_lease_per_unit'),
        ),
    ]
