# Generated by Django 5.2.7 on 2025-10-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lease_rename_no_of_bathrooms_unit_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(db_index=True, default='unkown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(db_index=True, default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
