# Generated by Django 5.2.7 on 2025-10-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domico_core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
